name: Build eResearch Job static page container image
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build website
        run: yarn build
      - name: Build storybook
        run: yarn build-storybook
      - name: Build container image
        run: docker build -t ghcr.io/eresearchqut/ai-toolbox/eresearch-job:latest -f containers/EresearchJob.Dockerfile .
      - name: Push container image
        run: docker push ghcr.io/eresearchqut/ai-toolbox/eresearch-job:latest
      - name: Send repository_dispatch event
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.QUT_SERVICE_ACCOUNT_TOKEN }}
          repository: "eresearchqut/${{ matrix.registry }}"
          event-type: build_job_images
