name: Build
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    name: Build, lint, and check formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Lint
        run: yarn lint
      - name: Check formatting
        run: yarn format:check
      - name: Build website
        run: yarn build
      - name: Test build storybook
        run: yarn build-storybook
